In [1]:
import numpy as np

print('Single Dimensional Array :')
print('---------------------------------------------------------------------------')
print('With all zeroes')
print(np.zeros(5,int))
print()
print('With all ones')
print(np.ones(5,int))
print()
print('With all random integers')
print(np.random.randint(1,10,5))
print()
print('With values within a range')
print(np.arange(1,10))
print()


print('Multi Dimensional Array :')
print('---------------------------------------------------------------------------')
print('With all zeroes')
print(np.zeros((4,3),int))
print()
print('With all ones')
print(np.ones((4,3),int))
print()
print('With all random integers')
print(np.random.randint(1,10,(4,3)))
print()
print('With values within a range')
print(np.arange(1,10).reshape(3,3))
print()
print('With diagonal element')
print(np.eye(4,None,0,int))
print()



Single Dimensional Array :
---------------------------------------------------------------------------
With all zeroes
[0 0 0 0 0]

With all ones
[1 1 1 1 1]

With all random integers
[6 7 4 1 9]

With values within a range
[1 2 3 4 5 6 7 8 9]

Multi Dimensional Array :
---------------------------------------------------------------------------
With all zeroes
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

With all ones
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

With all random integers
[[5 7 5]
 [7 9 9]
 [8 5 8]
 [6 2 7]]

With values within a range
[[1 2 3]
 [4 5 6]
 [7 8 9]]

With diagonal element
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

