In [1]:
import numpy as np
arr=np.random.randn(4,3)
print('Array:')
print('---------------------------------------------------------------------------')
print(arr)
print()
print('Size of Array:')
print('---------------------------------------------------------------------------')
print(arr.size)
print()
print('Size of particular row (row 2):')
print('---------------------------------------------------------------------------')
print(len(arr[:,2]))
print()
print('Size of particular column (column 2):')
print('---------------------------------------------------------------------------')
print(len(arr[2,:]))
print()
print('Taking input from file: ')
print('---------------------------------------------------------------------------')
with open('numpy2text.txt', 'r') as f:
    l =np.loadtxt(f)
print(l)
print()
print('Saving Array to a file: ')
print('---------------------------------------------------------------------------')
with open('numpy2output.txt', 'wb') as f:
    np.savetxt(f,arr)



Array:
---------------------------------------------------------------------------
[[ 1.74402322  0.09510149  0.32879187]
 [ 1.25908407 -1.16356907 -1.52914883]
 [-0.8525191  -2.35169062 -0.14136715]
 [ 2.87091006 -1.63035467 -1.45916641]]

Size of Array:
---------------------------------------------------------------------------
12

Size of particular row (row 2):
---------------------------------------------------------------------------
4

Size of particular column (column 2):
---------------------------------------------------------------------------
3

Taking input from file: 
---------------------------------------------------------------------------


FileNotFoundError: [Errno 2] No such file or directory: 'numpy2text.txt'