In [1]:
import numpy as np
mat1= np.random.randint(1,10,(3,3))
mat2= np.random.randint(1,10,(3,3))
print("Matrix 1:")
print(mat1)
print("Matrix 2:")
print(mat2)
print()
print('Addition of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1+mat2
print(mat3)
print()
print('Subtraction of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1+mat2
print(mat3)
print()
print('Multiplication of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1*mat2
print(mat3)
print()

mat1= np.random.randint(1,10,(4,3))
mat2= np.random.randint(1,10,(3,2))
print("Matrix 1:")
print(mat1)
print("Matrix 2:")
print(mat2)
print()
print('Element-by-Element Multiplication of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1.dot(mat2)
print(mat3)
print()
print('Displaying Specific Rows and column')
print('---------------------------------------------------------------------------')
print(mat3[1:,1:])


Matrix 1:
[[9 5 3]
 [5 9 2]
 [7 1 7]]
Matrix 2:
[[3 4 2]
 [9 5 3]
 [3 4 5]]

Addition of Two matrices
---------------------------------------------------------------------------
[[12  9  5]
 [14 14  5]
 [10  5 12]]

Subtraction of Two matrices
---------------------------------------------------------------------------
[[12  9  5]
 [14 14  5]
 [10  5 12]]

Multiplication of Two matrices
---------------------------------------------------------------------------
[[27 20  6]
 [45 45  6]
 [21  4 35]]

Matrix 1:
[[8 6 3]
 [9 5 5]
 [8 4 2]
 [9 2 1]]
Matrix 2:
[[7 9]
 [2 9]
 [8 3]]

Element-by-Element Multiplication of Two matrices
---------------------------------------------------------------------------
[[ 92 135]
 [113 141]
 [ 80 114]
 [ 75 102]]

Displaying Specific Rows and column
---------------------------------------------------------------------------
[[141]
 [114]
 [102]]
