In [1]:
import numpy as np

arr=np.random.randn(4,3)
print('Array:')
print('---------------------------------------------------------------------------')
print(arr)
print()
print('Absolute Value of the Array')
print('---------------------------------------------------------------------------')
print(np.absolute(arr))
print()
print('Negative Value of the Array')
print('---------------------------------------------------------------------------')
print(np.negative(arr))
print()
print('Array after deleting row 2')
print('---------------------------------------------------------------------------')
print(np.delete(arr,2,0))
print()
print('Array after deleting column 2')
print('---------------------------------------------------------------------------')
print(np.delete(arr,2,1))
print()
print('Maximum of Array')
print('---------------------------------------------------------------------------')
print(np.max(arr))
print()
print('Minimum of Array')
print('---------------------------------------------------------------------------')
print(np.min(arr))
print()
print('Sum of all elements of Array')
print('---------------------------------------------------------------------------')
print(np.sum(arr))
print()
print('Sum of all elements of Array row-wise')
print('---------------------------------------------------------------------------')
print(np.sum(arr,0))
print()
print('Sum of all elements of Array column-wise')
print('---------------------------------------------------------------------------')
print(np.sum(arr,1))


Array:
---------------------------------------------------------------------------
[[ 0.47931042  1.33672475  0.20620497]
 [ 0.02676083 -0.56931985 -0.2309934 ]
 [ 0.63985741 -0.68862413  0.21425858]
 [-1.29163495  1.47517853 -0.58108778]]

Absolute Value of the Array
---------------------------------------------------------------------------
[[0.47931042 1.33672475 0.20620497]
 [0.02676083 0.56931985 0.2309934 ]
 [0.63985741 0.68862413 0.21425858]
 [1.29163495 1.47517853 0.58108778]]

Negative Value of the Array
---------------------------------------------------------------------------
[[-0.47931042 -1.33672475 -0.20620497]
 [-0.02676083  0.56931985  0.2309934 ]
 [-0.63985741  0.68862413 -0.21425858]
 [ 1.29163495 -1.47517853  0.58108778]]

Array after deleting row 2
---------------------------------------------------------------------------
[[ 0.47931042  1.33672475  0.20620497]
 [ 0.02676083 -0.56931985 -0.2309934 ]
 [-1.29163495  1.47517853 -0.58108778]]

Array after deleting colu